### PR TITLE
Add markerclusterer

### PR DESCRIPTION
**Pull request by stefansl**
This is a basic draft for markerclusterer based on https://developers.google.com/maps/documentation/javascript/marker-clustering#maps_marker_clustering-javascript as mentioned here #27 

What do you think?

### CODE REVIEW

**Comment by bennyborn** [comment]
Just tested it, seems to work fine 👍 

Are you planning any further changes? Otherwise I would merge this request and provide the missing translations for the checkbox in tl_module.

**Comment by stefansl** [comment]
Maybe this PR is a little bit messed up. I guess i did not merge your last commits. So maybe I should clean it. What do you think?

**Comment by bennyborn** [comment]
I've noticed there are quite some changes included that I already did a week ago. If you'd like to polish it up a little go for it :)

**Comment by stefansl** [comment]
I want to check the markerclusterplus package https://github.com/googlemaps/js-markerclustererplus

So I have to install it via npm. Is it ok to place the package.json right next to composer.json and compile it into src/public?

**Comment by bennyborn** [comment]
That's absolutely fine!

**Pull request closed without merging**
